CREATE TABLE clients(
  `id` UNSIGNED INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `qrCodeUrl` VARCHAR(255) NOT NULL,
  `cardId` VARCHAR(255) NOT NULL,
  `userId` UNSIGNED INT,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)