CREATE TABLE reservations(
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `ownerId` INT UNSIGNED NOT NULL,
  `reviewStars` TINYINT,
  `reviewFeedback` VARCHAR(255),
  `finishedAt` TIMESTAMP NULL DEFAULT NULL,
  `roomId` INT UNSIGNED NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_room FOREIGN KEY (roomId) REFERENCES rooms (id)
)