CREATE TABLE reservations(
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ownerId` INT NOT NULL,
  `reviewStars` SMALLINT,
  `reviewFeedback` VARCHAR(255),
  `isUp` BOOLEAN NOT NULL,
  `roomId` INT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_room FOREIGN KEY (roomId) REFERENCES rooms (id)
)