CREATE TABLE reservations(
  `id` UNSIGNED INT AUTO_INCREMENT PRIMARY KEY,
  `ownerId` UNSIGNED INT NOT NULL,
  `reviewStars` TINYINT,
  `reviewFeedback` VARCHAR(255),
  `finishedAt` TIMESTAMP DEFAULT NULL,
  `roomId` UNSIGNED INT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_room FOREIGN KEY (roomId) REFERENCES rooms (id)
)