CREATE DATABASE biblioteca;

-- Creación de Tablas
CREATE TABLE rooms(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(31),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)